In [15]:
import numpy as np

In [16]:
a1 = np.array([[1, 2, 3.3],
              [4, 5, 6.3]])

In [20]:
a1,a1.shape,a1.ndim

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.3]]),
 (2, 3),
 2)

In [26]:
a2 = np.array([[[1, 2, 3.3],
              [4, 5, 6.3]],
              [[1, 2, 3.3],
              [4, 5, 6.3]]])

In [21]:
a2.shape,a2.ndim

((2, 2, 3), 3)

In [22]:
a1.shape, a1.dtype, a1.size

((2, 3), dtype('float64'), 6)

In [23]:
a2.shape, a2.dtype, a2.size, type(a2)

((2, 2, 3), dtype('float64'), 12, numpy.ndarray)

## create df from numpy

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame(a1)

In [33]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.3

# create array

In [34]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
ones.dtype

dtype('float64')

In [36]:
type(ones)

numpy.ndarray

In [37]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
range_array = np.arange(0, 10, 2)

In [39]:
range_array

array([0, 2, 4, 6, 8])

In [40]:
random_array = np.random.randint(0, 10, size=(3,5))

In [41]:
random_array

array([[5, 4, 3, 3, 9],
       [1, 6, 0, 9, 5],
       [8, 3, 6, 1, 0]])

In [42]:
random_array.size

15

In [44]:
random_array_2 = np.random.random((5,3))

In [45]:
random_array_2

array([[0.03914215, 0.73376828, 0.06225515],
       [0.2887807 , 0.55928853, 0.56087093],
       [0.81726106, 0.10577562, 0.266244  ],
       [0.42942762, 0.90719377, 0.83868511],
       [0.12374727, 0.87840612, 0.55734267]])

In [46]:
random_array_3 = np.random.rand(5,3)

In [47]:
random_array_3

array([[0.10099736, 0.35326774, 0.46116339],
       [0.34752285, 0.38478937, 0.8007219 ],
       [0.3129624 , 0.89739126, 0.96584042],
       [0.61138492, 0.20132664, 0.68036647],
       [0.8605093 , 0.64112776, 0.59213381]])

## pseudo random number

In [61]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [62]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

### viewing array and numbers

In [63]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [66]:
a1[0]

array([1. , 2. , 3.3])

In [68]:
a2

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.3]],

       [[1. , 2. , 3.3],
        [4. , 5. , 6.3]]])

In [70]:
a2.shape

(2, 2, 3)

In [71]:
a2[0]

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [73]:
a2[:2, :2, :2]

array([[[1., 2.],
        [4., 5.]],

       [[1., 2.],
        [4., 5.]]])

In [74]:
a4 = np.random.randint(10, size= (2,3, 4, 5))

In [75]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [77]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [79]:
a4[:, : , : , :1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

### manipulating and comparing arrays

In [82]:
ones = np.ones(3)
ones_copy  = np.ones(3)

In [83]:
ones

array([1., 1., 1.])

In [84]:
ones + ones_copy

array([2., 2., 2.])

In [85]:
a2

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.3]],

       [[1. , 2. , 3.3],
        [4. , 5. , 6.3]]])

In [86]:
a2 = a1

In [87]:
a1 = np.array([1,2,3])

In [88]:
a1

array([1, 2, 3])

In [89]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [90]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18.9]])

In [91]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [93]:
a3 = np.array([[[1, 2, 3.3],
              [4, 5, 6.3]],
              [[1, 2, 3.3],
              [4, 5, 6.3]]])

In [94]:
a3

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.3]],

       [[1. , 2. , 3.3],
        [4. , 5. , 6.3]]])

In [95]:
a2*a3

array([[[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 39.69]],

       [[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 39.69]]])

In [96]:
a2.shape, a3.shape

((2, 3), (2, 2, 3))

In [99]:
#floor division
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [100]:
a2/a1

array([[1. , 1. , 1.1],
       [4. , 2.5, 2.1]])

In [101]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [103]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 39.69]])

In [104]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 39.69]])

In [105]:
a1+ones

array([2., 3., 4.])

In [106]:
np.add(a1, ones)

array([2., 3., 4.])

In [107]:
a1%2

array([1, 0, 1])

In [108]:
a1

array([1, 2, 3])

In [109]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [110]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### aggregation

In [112]:
listy_list = [1,2,3]
type(listy_list)

list

In [113]:
sum(listy_list)

6

In [114]:
a1

array([1, 2, 3])

In [116]:
np.sum(a1),sum(a1)

(6, 6)

In [118]:
massive_array = np.random.random(100000)
massive_array.shape

(100000,)

In [119]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.93 ms ± 548 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.2 µs ± 781 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [120]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [122]:
np.mean(a2)

3.6

In [123]:
np.max(a2)

6.3

In [124]:
np.std(a2)

1.7710637105046974

In [125]:
np.var(a2)

3.1366666666666663

In [126]:
np.sqrt(np.var(a2))

1.7710637105046974

### reshaping and transposing

In [127]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [128]:
a2.shape

(2, 3)

In [129]:
a3.shape

(2, 2, 3)

In [135]:
a2_reshape = a2.reshape(1,2,3)

In [136]:
a2_reshape*a3

array([[[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 39.69]],

       [[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 39.69]]])

In [137]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [139]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.3]])

In [140]:
a3.shape

(2, 2, 3)

In [141]:
a3.T.shape

(3, 2, 2)

In [142]:
a3

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.3]],

       [[1. , 2. , 3.3],
        [4. , 5. , 6.3]]])

In [143]:
a3.T

array([[[1. , 1. ],
        [4. , 4. ]],

       [[2. , 2. ],
        [5. , 5. ]],

       [[3.3, 3.3],
        [6.3, 6.3]]])

## DOT Product

In [148]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [149]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [151]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [152]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [153]:
# element wise multiply
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [156]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [157]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [158]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [159]:
mat3 = np.dot(mat1, mat2.T)

In [160]:
mat3.shape, mat3

((5, 5),
 array([[ 51,  55,  72,  20,  15],
        [130,  76, 164,  33,  44],
        [ 67,  39,  85,  27,  34],
        [115,  69, 146,  37,  47],
        [111,  77, 145,  56,  64]]))

## dot product example

In [163]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
price = np.array([10, 8, 12])

In [164]:
sales_amount, price

(array([[12, 15,  0],
        [ 3,  3,  7],
        [ 9, 19, 18],
        [ 4,  6, 12],
        [ 1,  6,  7]]),
 array([10,  8, 12]))

In [167]:
price.shape, sales_amount.shape

((3,), (5, 3))

In [171]:
np.dot(price,sales_amount )

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [178]:
np.dot(price,sales_amount.T)

array([240, 138, 458, 232, 142])

## comparison operators

In [179]:
a1

array([1, 2, 3])

In [180]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [182]:
a1 <= a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [183]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

### sorting arrays

In [193]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [194]:
np.sort(random_array)

array([[0, 0, 2, 4, 7],
       [4, 5, 5, 6, 8],
       [1, 1, 4, 8, 9]])

In [197]:
random_array

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [198]:
np.argsort(random_array)

array([[2, 3, 1, 4, 0],
       [4, 0, 1, 2, 3],
       [0, 4, 1, 3, 2]])

In [199]:
a1

array([1, 2, 3])

In [200]:
np.argsort(a1)

array([0, 1, 2])

In [201]:
np.argmin(a1)

0

In [202]:
np.argmax(a1)

2

In [203]:
random_array

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]])

In [206]:
np.argmax(random_array, axis=1)

array([0, 3, 2])

### practical example

In [214]:
from matplotlib.image import imread
panda = imread('Grosser_Panda.jpeg')
print(type(panda))

<class 'numpy.ndarray'>


<img src = 'Grosser_Panda.jpeg'/>

In [217]:
panda.shape, panda.size, panda.ndim

((2617, 3550, 3), 27871050, 3)